import { config } from "dotenv";
import { subDays, eachDayOfInterval, format } from "date-fns";
import { convertAmountToMiliunits } from "@/lib/utils";

import { categories, accounts, transactions } from "@/db/schema";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";

config({ path: ".env.local" });

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const SEED_USER_ID = "user_2ggy6LW3YjOsr0Ocx8WxA4SFxSL"; // my Clerk auth userId
const SEED_CATEGORIES = [
  {
    id: "category_1",
    name: "Alimentação",
    userId: SEED_USER_ID,
    plaidId: null,
  },
  { id: "category_2", name: "Renda", userId: SEED_USER_ID, plaidId: null },
  { id: "category_3", name: "Acessórios", userId: SEED_USER_ID, plaidId: null },
  { id: "category_4", name: "Roupa", userId: SEED_USER_ID, plaidId: null },
  { id: "category_5", name: "Transporte", userId: SEED_USER_ID, plaidId: null },
  { id: "category_6", name: "Saúde", userId: SEED_USER_ID, plaidId: null },
  {
    id: "category_7",
    name: "Entretenimento",
    userId: SEED_USER_ID,
    plaidId: null,
  },
  { id: "category_8", name: "Outros", userId: SEED_USER_ID, plaidId: null },
];

const SEED_ACCOUNTS = [
  {
    id: "account_1",
    name: "Conta à ordem",
    userId: SEED_USER_ID,
    plaidId: null,
  },
  { id: "account_2", name: "Poupanças", userId: SEED_USER_ID, plaidId: null },
];

const defaultTo = new Date();
const defaultFrom = subDays(defaultTo, 90);

const SEED_TRANSACTIONS: (typeof transactions.$inferSelect)[] = [];

const generateRandomAmount = (category: typeof categories.$inferInsert) => {
  switch (category.name) {
    case "Renda":
      return Number((Math.random() * 400 + 90).toFixed(2)); // Rent will likely be a larger amount
    case "Acessórios":
      return Number((Math.random() * 200 + 50).toFixed(2));
    case "Alimentação":
      return Number((Math.random() * 30 + 10).toFixed(2));
    case "Transporte":
    case "Saúde":
      return Number((Math.random() * 50 + 15).toFixed(2));
    case "Entretenimento":
    case "Roupa":
    case "Outros":
      return Number((Math.random() * 100 + 20).toFixed(2));
    default:
      return Number((Math.random() * 50 + 10).toFixed(2));
  }
};

const generateTransactionsForDay = (day: Date) => {
  const numTransactions = Math.floor(Math.random() * 4) + 1; // 1 to 4 transactions per day
  for (let i = 0; i < numTransactions; i++) {
    const category =
      SEED_CATEGORIES[Math.floor(Math.random() * SEED_CATEGORIES.length)];
    const isExpense = Math.random() > 0.6; // 60% chance of being an expense
    const amount = generateRandomAmount(category);
    const formattedAmount = convertAmountToMiliunits(
      isExpense ? -amount : amount
    ); // Negative for expenses

    SEED_TRANSACTIONS.push({
      id: `transaction_${format(day, "yyyy-MM-dd")}_${i}`,
      accountId: SEED_ACCOUNTS[0].id, // Assuming always using the first account for simplicity
      categoryId: category.id,
      date: day,
      amount: Math.ceil(formattedAmount),
      payee: "Merchant",
      notes: "Autogenerated transaction via seed.ts",
    });
  }
};

const generateTransactions = () => {
  const days = eachDayOfInterval({ start: defaultFrom, end: defaultTo });
  days.forEach((day) => generateTransactionsForDay(day));
};

generateTransactions();

const main = async () => {
  try {
    // Reset database
    await db.delete(transactions).execute();
    await db.delete(accounts).execute();
    await db.delete(categories).execute();
    // Seed categories
    await db.insert(categories).values(SEED_CATEGORIES).execute();
    // Seed accounts
    await db.insert(accounts).values(SEED_ACCOUNTS).execute();
    // Seed transactions
    await db.insert(transactions).values(SEED_TRANSACTIONS).execute();
  } catch (error) {
    console.error("Error during seed:", error);
    process.exit(1);
  }
};

main();
